### ISSUE TITLE
Server crashes when a client sends exactly 2^16 bytes binary data

### ISSUE THREAD

**Issue by kazuyukitanimura** [LearnBoost/websocket.io#14]
Is it supposed to be ">=" instead of ">" at  line 189 in lib/protocols/ hybi-16.js  ?

The error message that I got follows. Once I corrected the line manually in node_modules, it worked.
Thanks

assert.js:104
  throw new assert.AssertionError({
        ^
AssertionError: value is larger than maximum value for type
    at verifuint (buffer.js:821:10)
    at writeUInt16 (buffer.js:859:5)
    at Buffer.writeUInt16BE (buffer.js:876:3)
    at WebSocket.frame (/Users/kazuyukitanimura/Documents/git/websocket.io-binaryTransferBenchmark/node_modules/websocket.io/lib/protocols/hybi-16.js:205:20)
    at WebSocket.write (/Users/kazuyukitanimura/Documents/git/websocket.io-binaryTransferBenchmark/node_modules/websocket.io/lib/protocols/hybi-16.js:150:20)
    at WebSocket.send (/Users/kazuyukitanimura/Documents/git/websocket.io-binaryTransferBenchmark/node_modules/websocket.io/lib/socket.js:88:8)
    at WebSocket.<anonymous> (/Users/kazuyukitanimura/Documents/git/websocket.io-binaryTransferBenchmark/websocket.io-app.js:25:16)
    at WebSocket.emit (events.js:67:17)
    at WebSocket.onMessage (/Users/kazuyukitanimura/Documents/git/websocket.io-binaryTransferBenchmark/node_modules/websocket.io/lib/socket.js:76:8)
    at Receiver.<anonymous> (/Users/kazuyukitanimura/Documents/git/websocket.io-binaryTransferBenchmark/node_modules/websocket.io/lib/protocols/hybi-16.js:43:12)

**Comment by 3rd-Eden** [comment]
Which version of `WebSocket.io` are you running?

**Comment by kazuyukitanimura** [comment]
WebSocket.io@0.1.1 with node@v0.6.5

For client, I used WebSocket-Node@1.0.2

Thanks

**Comment by Befzz** [comment]
@kazuyukitanimura you are right, 65536 is 0x100000000 17bit ;)

```
if (dataLength > 65536) {
```

must be

```
if (dataLength > 65535) {
```

or

```
if (dataLength >= 65536) {
```

**hybi-07-12.js** also have this issue

**Comment by einaros** [comment]
This was fixed some time ago in ws (http://github.com/einaros/ws). I will get around to bringing the newest parsers from there.
