### ISSUE TITLE
Error handling must be reworked

### ISSUE THREAD

**Issue by nicokaiser** [LearnBoost/websocket.io#37]
The error handling is completely broken.

I'm getting random "Error: write EPIPE" and "Error: This socket is closed." from websocket.io which completely crashes the application, even tough I have "error" handlers for wsio sockets.

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: write EPIPE
    at errnoException (net.js:670:11)
    at Object.afterWrite [as oncomplete] (net.js:503:19)
```

```
Error: This socket is closed.
    at Socket._write (net.js:474:19)
    at Socket.write (net.js:466:15)
    at WebSocket.write (/opt/services/webpush/support/webpush-engine/node_modules/websocket.io/lib/protocols/drafts.js:194:23)
    at WebSocket.send (/opt/services/webpush/support/webpush-engine/node_modules/websocket.io/lib/socket.js:104:8)
    at WebPush._doBroadcast (/opt/services/webpush/lib/webpush.js:295:34)
    at Array.0 (/opt/services/webpush/lib/webpush.js:304:12)
    at EventEmitter._tickCallback (node.js:192:40)
```

I cannot tell if this is emitted by ws or by the "drafts" handler, as I cannot reproduce without live clients...

**Comment by rauchg** [comment]
Maybe your application is trying to write after the socket has closed ?
Are you suggesting we check for `.open == true` in the write method to avoid this?

**Comment by nicokaiser** [comment]
This would explain the second error, but EPIPE? I'll try to find if I'm writing after close...

**Comment by rauchg** [comment]
Actually, we're already checking for open

**Comment by nicokaiser** [comment]
Question is, if wsio should check for readyState=='open' (as wsio may not have noticed the socket is closed yet)

**Comment by rauchg** [comment]
I think it should

**Comment by nicokaiser** [comment]
I added this to https://github.com/nicokaiser/websocket.io/commit/48c82a809b425f78666570c41a35d1598777b851 (which unfortunately went to pull #36)

**Comment by nicokaiser** [comment]
Ok together with https://github.com/einaros/ws/pull/55 this should be fixed now.

**Comment by rauchg** [comment]
Very cool!
